name: Build & Deploy
on:
  push:
    branches: [main] # Trigger on pushes and merges to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PHP app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }} # Password of the user for SSH login
          script: |
            # Log that the deployment is starting
            echo "Starting deployment to ${{ secrets.SSH_HOST }} with user ${{ secrets.SSH_USERNAME }}"

            # Navigate to the deployment path
            cd ../var/www/html/ffmpeg

            # Pull the main branch (overwrite the existing files)
            git pull origin main

            # Install PHP dependencies (composer)
            composer install --no-interaction --prefer-dist

            # Install Node.js dependencies (yarn, if needed)
            yarn install --frozen-lockfile

            # Restart Apache service
            sudo systemctl restart apache2

            echo 'Deployment successfully'