name: Build & Deploy
on:
  push:
    branches: [main] # Trigger on pushes and merges to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PHP app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            # Navigate to the deployment path
            cd /var/www/html/ffmpeg

            # Clone the repository (overwrite the existing files)
            git clone https://github.com/tronish1189/AIC-Video-Library.git .

            # Install PHP dependencies (composer)
            composer install --no-interaction --prefer-dist

            # Install Node.js dependencies (yarn, if needed)
            yarn install --frozen-lockfile

            # Restart Apache service
            sudo systemctl restart apache2

            echo 'Deployment successful to server'
